### ISSUE TITLE
Issues with no description fail to unfurl since v0.6.0

### ISSUE THREAD

**Issue by joelsdc** [glensc/slack-unfurl-gitlab#6]
Hi, 

The fixes for #2 introduces a regression: If an issue doesn't have a description set, it will fail to unfurl with the following error:

```
[2018-10-19 18:38:03] unfurl.ERROR: Uncaught Exception TypeError: "Argument 1 passed to GitlabSlackUnfurl\Route\AbstractRouteHandler::sanitizeText() must be of the type string, null given, called in /app/vendor/glen/slack-unfurl-gitlab/src/Route/Issue.php on line 24" at /app/vendor/glen/slack-unfurl-gitlab/src/Traits/SanitizeTextTrait.php line 7 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to GitlabSlackUnfurl\\Route\\AbstractRouteHandler::sanitizeText() must be of the type string, null given, called in /app/vendor/glen/slack-unfurl-gitlab/src/Route/Issue.php on line 24 at /app/vendor/glen/slack-unfurl-gitlab/src/Traits/SanitizeTextTrait.php:7)"} []
```

I checked the code the commit that breaks it is: https://github.com/glensc/slack-unfurl-gitlab/pull/5/commits/8cd3b212097605c39159cb62021fce409a02edaf

Specifically here: https://github.com/glensc/slack-unfurl-gitlab/pull/5/commits/8cd3b212097605c39159cb62021fce409a02edaf#diff-7e2b8567c9d59205b305dc51a0d3b4cdR7 because it expects a string no matter what. 

Thanks!

**Comment by joelsdc** [comment]
+Info

Steps to reproduce:

1- Create a new issue in gitlab, leave description empty/unset.
2- Link that issue in slack.
3- You will see the error in the log.

If you link an issue that _does have a description_ or if you link a _note of a issue_, **both work correctly**.

Thanks!

**Comment by glensc** [comment]
tried to reproduce, seems it's empty string not `null` on gitlab.com: https://gitlab.com/api/v4/projects/glensc%2fplayground/issues?iids[]=1

![image](https://user-images.githubusercontent.com/199095/47286431-59800280-d5f7-11e8-9a1b-3cbe2913c353.png)

**Comment by glensc** [comment]
created fix: https://github.com/glensc/slack-unfurl-gitlab/pull/7

but github has some issues, gives 404 right now even the PR was created

![image](https://user-images.githubusercontent.com/199095/47287266-55a1af80-d5fa-11e8-9c0f-f36b3e606ccf.png)



will retry soon.

**Comment by glensc** [comment]
indeed. some bigger outage that even blog post is created: https://blog.github.com/2018-10-21-october21-incident-report/

![image](https://user-images.githubusercontent.com/199095/47291231-8e965000-d60b-11e8-974c-d3a38e75cf37.png)

**Comment by joelsdc** [comment]
Hi @glensc, although your branch `6-empty-desc` changes aren't merged yet, I tried them manually and I can confirm they fix the issue.

Can you kindly release v0.6.1 once merged for easy deployment?

Thanks for the quick response!

**Comment by glensc** [comment]
yes. some GitHub stability issues prevented me to see that PR.
